name: Build Signed APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Fix line endings and make gradlew executable
    - name: Fix gradlew line endings and permissions
      run: |
        # Convert Windows line endings to Unix if present
        sed -i 's/\r$//' gradlew
        chmod +x gradlew

    - name: Create keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

    - name: Build Signed APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-apk
        path: app/build/outputs/apk/release/app-release.apk